### ISSUE TITLE
liveries on add-on vehicles

### ISSUE THREAD

**Issue by jessemel** [alberttheprince/popcornrp-customs#24]
Are we not able to add/change liveries for add-on vehicles? I have a PD pack that I use and when I open the menu liveries are not an option anywhere. I can do all other customizations just not liveries

**Comment by alberttheprince** [comment]
Likely an issue with the car itself - liveries are working for custom and native vehicles as far as I can tell. Make sure you updated after the recent livery fix.

**Comment by jessemel** [comment]
@alberttheprince Yeah Im not sure it's updated, I downloaded it last night and tested it. The liveries work with the base qb-customs and was hoping this script would work as well just having the livery issue

I do know the liveries that are on this car pack are embedded textures and have to be used with texture tool to access them maybe that is why the script won't recognize the liveries?

**Comment by alberttheprince** [comment]
Are you able to share the files for the vehicles?  I can take a look at it if you can, I haven't run into any livery issues for any add-on vehicles myself.

**Comment by jessemel** [comment]
@alberttheprince sent via discord, thank you for your help

**Comment by alberttheprince** [comment]
This was closed, as the issue seems to be with how liveries are set up with the specific model that Jessemel is using, where they're seemingly embedded into the model. This seems to work with other vehicles that don't include liveries in the YTD, https://www.gta5-mods.com/vehicles/maibatsu-sunrise-r-add-on-tuning-liveries-sounds and may be an issue with this one specific instance of how liveries have been set up.
