### ISSUE TITLE
liveries on add-on police and ems pack

### ISSUE THREAD

**Issue by PapaKreller** [alberttheprince/popcornrp-customs#26]
Hi i downloaded this script today and everything works fine except the liveries i have a pd/ems pack from car-labs with liveries and they dont work but if i uses the integrated qb-mechanic i can use the liveries so i dont know what to do :/

**Comment by alberttheprince** [comment]
As it's likely an escrowed/locked resource we can't take a look at the resource. You likely have to reach out to the designer and see if they are willing to change how they handle liveries.

https://github.com/alberttheprince/popcornrp-customs/issues/24

See this issue, who had a similar issue with vehicle liveries. If you can share info about how the liveries are stored in the vehicle files we can maybe take a look at it, but otherwise we can't do much with this info.

**Comment by PapaKreller** [comment]
the liveries are not escrowed/locked they are fully customizable and they are in the stream folder with all other files

**Comment by alberttheprince** [comment]
Yes but as I said, I'm not going to buy them/you cannot share them with me, so we cannot look into this. 

If you can work with the original designer and PR a change to use liveries how they're organized in this pack we can accept it, but it's not possible to check how they organized their livery files without the files themself.

**Comment by PapaKreller** [comment]
where can i share them ? because i just talked to them and the liveriers should work like gta vanilla cars and i just tryed with another script and that worked i just like the way that popcornrp-customs looks like :)

**Comment by alberttheprince** [comment]
If you want you can have the designer contact me via discord: noornahas, and I can discuss it with them. You're not allowed to share files without permission of the designer.

**Comment by PapaKreller** [comment]
i will try to contact them again

**Comment by alberttheprince** [comment]
Were you able to contact them? I didn't receive any messages.

**Comment by alberttheprince** [comment]
Closing this issue, if you can please get the creator to reach out to me.
